### ISSUE TITLE
Docker image exakat latest is failing with : gremlin-groovy is not an available GremlinScriptEngine 

### ISSUE THREAD

**Issue by maxerbox** [exakat/exakat-docker#20]
Image tag : latest 2/25/2020
Here are my logs :
``` 
Error : The script submitted for processing evaluated in the ScriptEngine with errors and could not be processed. Check the script submitted for syntax errors or other problems and then resubmit. : gremlin-groovy is not an available GremlinScriptEngine
===================  SERVER TRACE  ========================= 
array (
  'stackTrace' => 'java.lang.IllegalArgumentException: gremlin-groovy is not an available GremlinScriptEngine
	at org.apache.tinkerpop.gremlin.jsr223.CachedGremlinScriptEngineManager.registerLookUpInfo(CachedGremlinScriptEngineManager.java:95)
	at org.apache.tinkerpop.gremlin.jsr223.CachedGremlinScriptEngineManager.getEngineByName(CachedGremlinScriptEngineManager.java:58)
	at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$0(GremlinExecutor.java:267)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
',
  'exceptions' => 
  array (
    0 => 'java.lang.IllegalArgumentException',
  ),
)
 ============================================================ 
 
on file phar:///usr/src/exakat/exakat/vendor/brightzone/gremlin-php/src/Connection.php
on line 847
```

**Comment by sirio3mil** [comment]
Same error here, code is perfectly fine 

`Loading with \Exakat\Loader\SplitGraphson
111/118 [================================================================>----] 94.07% 00:00:02
Error : The script submitted for processing evaluated in the ScriptEngine with errors and could not be processed. Check the script submitted for syntax errors or other problems and then resubmit. : gremlin-groovy is not an available GremlinScriptEngine

 ===================  SERVER TRACE  =========================
array (
  'stackTrace' => 'java.lang.IllegalArgumentException: gremlin-groovy is not an available GremlinScriptEngine
        at org.apache.tinkerpop.gremlin.jsr223.CachedGremlinScriptEngineManager.registerLookUpInfo(CachedGremlinScriptEngineManager.java:95)
        at org.apache.tinkerpop.gremlin.jsr223.CachedGremlinScriptEngineManager.getEngineByName(CachedGremlinScriptEngineManager.java:58)
        at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$0(GremlinExecutor.java:267)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
',
  'exceptions' =>
  array (
    0 => 'java.lang.IllegalArgumentException',
  ),
)
 ============================================================

on file phar:///usr/src/exakat/exakat/vendor/brightzone/gremlin-php/src/Connection.php
on line 847`

Latest processed file is an empty interface and next one is a class already used an tested.

**Comment by sirio3mil** [comment]
Using exakat/exakat:2.0.9 everything works fine, also, notice that image with exakat 2.1.2 have 381 MB and with 2.0.9 there are more than 600, big change for a minor version right?

**Comment by evs-ch** [comment]
Seems like all that's needed is:

```diff
diff --git a/Dockerfile b/Dockerfile
index 35617d9..54eaba1 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -3,6 +3,7 @@ FROM php:7.4-cli-buster
 LABEL MAINTAINER Exakat, Damien Seguy, dseguy@exakat.io
 ENV EXAKAT_VERSION 2.1.2
 ENV GREMLIN_VERSION 3.4.7
+ENV GREMLIN_NEO4J_VERSION 3.4.7
 
 ENV PATH="/usr/src/exakat/:${PATH}"
 
```

That got removed in 8e1ecca05027527cdb7cce011e95b37d746b8eac, for some reason. Works again for me at least when built with this patch applied.
