### ISSUE TITLE
Any plans to update docker image to use latest version of exakat?

### ISSUE THREAD

**Issue by itbecomesfluid** [exakat/exakat-docker#23]
Hi,

I notice this docker version uses version 2.1.9 of exakat.  The latest version of exakat is currently 2.3.0 based on list at https://www.exakat.io/versions/index.php

Any plans to upgrade the docker image accordingly?

Thanks.

**Comment by itbecomesfluid** [comment]
Forgot to mention, I did try this myself.

I changed just the EXAKAT variable to 2.3.0 in Dockerfile and created a new image.

However on trying to run exakat on a project, it returns an error:

```
Fatal error: Uncaught TypeError: Return value of Brightzone\GremlinDriver\RequestMessage::jsonSerialize() must be an instance of Brightzone\GremlinDriver\mixed, array returned in phar:///usr/src/exakat/exakat/vendor/brightzone/gremlin-php/src/RequestMessage.php:60
Stack trace:
#0 [internal function]: Brightzone\GremlinDriver\RequestMessage->jsonSerialize()
#1 phar:///usr/src/exakat/exakat/vendor/brightzone/gremlin-php/src/Serializers/Json.php(35): json_encode(Object(Brightzone\GremlinDriver\RequestMessage), 256)
#2 phar:///usr/src/exakat/exakat/vendor/brightzone/gremlin-php/src/Message.php(189): Brightzone\GremlinDriver\Serializers\Json->serialize(Object(Brightzone\GremlinDriver\RequestMessage))
#3 phar:///usr/src/exakat/exakat/vendor/brightzone/gremlin-php/src/Connection.php(184): Brightzone\GremlinDriver\Message->buildMessage()
#4 phar:///usr/src/exakat/exakat/vendor/brightzone/gremlin-php/src/Connection.php(482): Brightzone\GremlinDriver\Connection->writeSocket()
#5 phar:///usr/src/exakat/exakat/ven
```

Please find below the output of exakat doctor:

```
Warning: mkdir(): phar error: cannot create directory "phar:///usr/src/exakat/exakat/stubs", write operations disabled in phar:///usr/src/exakat/exakat/library/Exakat/Tasks/Doctor.php on line 250
exakat :
    executable           : /usr/src/exakat//exakat
    version              : 2.3.0
    build                : 1265
    exakat.ini           : .usr.src.exakat.config.exakat.ini
    graphdb              : gsneo4j
    reports              :
    rulesets             : CompatibilityPHP53,
                           CompatibilityPHP54,
                           CompatibilityPHP55,
                           CompatibilityPHP56,
                           CompatibilityPHP70,
                           CompatibilityPHP71,
                           CompatibilityPHP72,
                           CompatibilityPHP73,
                           CompatibilityPHP74,
                           CompatibilityPHP80,
                           Analyze,
                           Preferences,
                           Appinfo,
                           Appcontent,
                           Dead code,
                           ClassReview,
                           Performances,
                           Security,
                           Custom,
                           Inventory,
                           Stats,
                           php-cs-fixable,
                           Rector
    extra rulesets       :
    ignored rules        :
    tokenslimit          : 100 000 000
    stubs                :

PHP :
    binary               : 7.4.27
    memory_limit         : -1
    short_open_tags      : Off
    ext/curl             : Yes
    ext/hash             : Yes
    ext/phar             : Yes
    ext/sqlite3          : Yes
    ext/tokenizer        : Yes
    ext/mbstring         : Yes
    ext/json             : Yes
    ext/xmlwriter        : Yes
    pcre.jit             : On (Must be off on PHP 7.3 and OSX)

java :
    installed            : Yes
    type                 : OpenJDK Runtime Environment (build 11.0.13+8-post-Debian-1deb10u1)
    version              : openjdk
    $JAVA_HOME           : <none>
    $JAVA_OPTIONS        :

tinkergraph :
    configured           : No tinkergraph configured in config/exakat.ini.

tinkergraphv3 :
    configured           : No tinkergraph configured in config/exakat.ini.

gsneo4j :
    installed            : Yes (folder : /usr/src/exakat/tinkergraph)
    host                 : 127.0.0.1
    port                 : 8182
    gremlin version      : 3.4.8
    neo4j version        : 3.2.3

gsneo4jv3 :
    configured           : No gsneo4jv3_folder configured in config/exakat.ini.

nogremlin :
    installed            : Always

project :
    name                 :
    url                  :
    phpversion           : 7.4
    reports              : ""
    rulesets             : CompatibilityPHP53, CompatibilityPHP54, CompatibilityPHP55, CompatibilityPHP56, CompatibilityPHP70, CompatibilityPHP71, CompatibilityPHP72, CompatibilityPHP73, CompatibilityPHP74, CompatibilityPHP80, Analyze, Preferences, Appinfo, Appcontent, Dead code, ClassReview, Performances, Security, Custom, Inventory, Stats, php-cs-fixable, Rector
    included dirs        :
    ignored dirs         : /assets, /cache, /css, /data, /doc, /docker, /docs, /example, /examples, /images, /js, /lang, /spec, /sql, /test, /tests, /tmp, /version, /var
    ignored rules        :
    file extensions      : php, php3, inc, tpl, phtml, tmpl, phps, ctp, module

folders :
    projects folder      : Yes

php74 :
    configured           : Yes (/usr/local/bin/php)
    actual version       : 7.4.27
    auditing             : with this version
```

Thanks in advance for any help.

**Comment by itbecomesfluid** [comment]
I closed this as I'm happy with 2.1.9 as the version used in docker
